

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:

    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    hibernate:

      ddl-auto: update
    show-sql: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/officeassistant

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:officeAssistant
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

---

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

---

